version: '2'
services:

  app:
    build: app/.
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:supersecure@db/testing123
      FLASK_ENV: development

  db:
    build: db/.
    volumes:
      - /var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: supersecure
