version: '2'
services:

  app:
    build: app/.
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db

  db:
    build: db/.
    volumes:
      - /var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: supersecure
